from rest_framework import serializers
from .models import Order, OrderItem


class OrderItemSerializer(serializers.ModelSerializer):
    product_name = serializers.CharField(source='product.name', read_only=True)
    subtotal = serializers.DecimalField(
        max_digits=10, decimal_places=2, read_only=True
    )

    class Meta:
        model = OrderItem
        fields = [
            'id', 'product', 'product_name',
            'quantity', 'price_at_purchase', 'subtotal'
        ]


class OrderSerializer(serializers.ModelSerializer):
    items = OrderItemSerializer(many=True, read_only=True)
    status_display = serializers.CharField(
        source='get_status_display',
        read_only=True
        # get_status_display() is auto-generated by Django for CharField with choices.
        # It returns the human-readable label: 'PAID' → 'Paid'
    )

    class Meta:
        model = Order
        fields = [
            'id', 'status', 'status_display', 'total_amount',
            'shipping_address', 'items', 'created_at'
        ]
        read_only_fields = ['status', 'total_amount', 'created_at']


class OrderCreateSerializer(serializers.Serializer):
    """
    WHY a plain Serializer and not ModelSerializer here?
    ──────────────────────────────────────────────────────
    Order creation is NOT a simple model field mapping.
    It's a complex multi-step operation handled by the service.
    A plain Serializer just validates the input (shipping address).
    The service does all the real work.
    """
    shipping_address = serializers.CharField(required=False, default='')